name: Stable Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: |
        apt-get update
        apt-get install -yqq --no-install-recommends --no-install-suggests \
            ca-certificates build-essential cmake ninja-build git \
            libicu-dev libexpat1-dev libinih-dev nlohmann-json3-dev \
            libsdl2-dev libpng-dev libpixman-1-dev libfmt-dev \
            libfreetype6-dev libharfbuzz-dev libmpg123-dev libsndfile-dev \
            libvorbis-dev libopusfile-dev libspeexdsp-dev \
            expat meson \
            libdrm-dev libgbm-dev # only needed for sdl2 on debian 11
        git clone --recursive https://github.com/benhoyt/inih.git
        cd inih
        mkdir 3ds
        cd 3ds 
        meson .. 
        meson install
        cd ../..
        git clone --recursive https://github.com/libexpat/libexpat.git
        cd libexpat/expat
        cmake .
        make install
        cd ../..
        git clone --recursive https://github.com/EasyRPG/liblcf
        cd liblcf
        cmake . -B 3dsout
        cd 3dsout
        make install
        cd ../..
        cmake -S . -B 3dsout -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake -DCMAKE_MODULE_PATH=Findliblcf.cmake -DCMAKE_PREFIX_PATH=liblcf -Dliblcf_DIR=/usr/local/lib/cmake/liblcf
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
    # Artifact name
        name: 3ds
    # A file, directory or wildcard pattern that describes what to upload
        path: 3dsout
    # The desired behavior if no files are found using the provided path.
