name: Stable Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: 
        export rpgdir="${PWD}/3DSRPG" && \
        mkdir "$rpgdir" \
        && \
        apt-get update && \
        apt-get install -yqq --no-install-recommends --no-install-suggests \
           ca-certificates build-essential cmake ninja-build git \
           libicu-dev libexpat1-dev libinih-dev nlohmann-json3-dev \
           libsdl2-dev libpng-dev libpixman-1-dev libfmt-dev \
           libfreetype6-dev libharfbuzz-dev libmpg123-dev libsndfile-dev \
           libvorbis-dev libopusfile-dev libspeexdsp-dev \
           expat meson \
           libdrm-dev libgbm-dev \
        && \
        (cd "$rpgdir" && \
        git clone --recursive https://github.com/benhoyt/inih.git "$rpgdir/inih" && \
        cd "$rpgdir/inih" && \
        mkdir 3ds && \
        cd 3ds && \
        meson .. && \
        meson install && \
        cd ../.. &) \
        && \
        (cd "$rpgdir" && \
        git clone --recursive https://github.com/libexpat/libexpat.git "$rpgdir/libexpat" && \
        cd "$rpgdir/libexpat/expat" && \
        cmake . && \
        make install -j42069 && \
        cd ../.. &) \
        && \
        (cd "$rpgdir" && \
        git clone --recursive https://github.com/EasyRPG/liblcf "$rpgdir/liblcf" && \
        cd liblcf && \
        cmake . -B 3dsout -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake && \
        cd 3dsout && \
        make install -j42069 && \
        cd ../.. &) \
        && \
        (cd "$rpgdir" && \
        git clone --recursive https://github.com/EasyRPG/Player "$rpgdir/Player" && \
        cd Player && \
        cmake -S . -B 3dsout -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake \
        && \
        cd "$rpgdir/../" &) \
        && \
        cmake -S . -B 3dsout -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake && \
        echo done;
    - name: make final
      run: make -j42069
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
    # Artifact name
        name: 3ds
    # A file, directory or wildcard pattern that describes what to upload
        path: "$rpgdir"
    # The desired behavior if no files are found using the provided path.
